services:
  mysql:
    image: mysql:8.0.20
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    volumes:
      - mysql-python-task-2:/var/lib/mysql
      - ./test-dumps/sakila-db(mysql):/home
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - python-task-2-network

#  mysql2:
#    image: mysql:8.0.20
#    container_name: ${PROJECT_NAME}-mysql2
#    restart: unless-stopped
#
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    networks:
#      - python-task-2-network

  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-postgres
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-python-task-2:/var/lib/postgresql/data
      - ./test-dumps/northwind-db(postgres):/home
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - python-task-2-network

#  postgres2:
#    image: postgres:latest
#    container_name: ${PROJECT_NAME}-postgres2
#    restart: unless-stopped
#    user: postgres
#
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DATABASE}
#    networks:
#      - python-task-2-network

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: ${PROJECT_NAME}-pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      networks:
        - python-task-2-network



networks:
  python-task-2-network:

volumes:
  mysql-python-task-2:

  postgres-python-task-2:
