services:
  mysql:
    image: mysql:8.0.20
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
      - ./test-dumps/sakila-db(mysql):/home
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - python-task-2-network

  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-postges
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - python-task-2-network

networks:
  python-task-2-network:

volumes:
  mysql:
  postgres: